### ISSUE TITLE
Kate's Bio

### ISSUE THREAD

**Issue by cbattista** [StanfordCosyne/onboarding#16]
This is the beginning of the github onboarding exercises -https://github.com/StanfordCosyne/onboarding/wiki/Github-Onboarding-Exercise

**Comment by kd997** [comment]
What is the point of opening an issue in the command window? I can comment and close the issue without ever having opened it... <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cbattista** [comment]
Are you using this - http://nodegh.io/? I've actually never used this, but
I'll check it out...

**Comment by kd997** [comment]
Yes! Its great!!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cbattista** [comment]
Cool maybe you can give me a quick tour tomorrow...
